if( ECCODES_IS_BUILD_DIR_EXPORT )
  set( ECCODES_DEFINITION_PATH  /usr/local/components/MBU-1.0/lib/eccodes/eccodes-2.1.0-Source/build/share/eccodes/definitions )
  set( ECCODES_SAMPLES_PATH     /usr/local/components/MBU-1.0/lib/eccodes/eccodes-2.1.0-Source/build/share/eccodes/samples )
  set( ECCODES_IFS_SAMPLES_PATH /usr/local/components/MBU-1.0/lib/eccodes/eccodes-2.1.0-Source/build/share/eccodes/ifs_samples )
else()
  set( ECCODES_DEFINITION_PATH  /usr/local/components/MBU-1.0/lib/eccodes/share/eccodes/definitions )
  set( ECCODES_SAMPLES_PATH     /usr/local/components/MBU-1.0/lib/eccodes/share/eccodes/samples )
  set( ECCODES_IFS_SAMPLES_PATH /usr/local/components/MBU-1.0/lib/eccodes/share/eccodes/ifs_samples )
endif()
