if( ECCODES_IS_BUILD_DIR_EXPORT )
  set( ECCODES_DEFINITION_PATH  /data/GIOVANNA/ECCODES/build/share/eccodes/definitions )
  set( ECCODES_SAMPLES_PATH     /data/GIOVANNA/ECCODES/build/share/eccodes/samples )
  set( ECCODES_IFS_SAMPLES_PATH /data/GIOVANNA/ECCODES/build/share/eccodes/ifs_samples )
else()
  set( ECCODES_DEFINITION_PATH  /usr/local/components/MBU/lib/eccodes/share/eccodes/definitions )
  set( ECCODES_SAMPLES_PATH     /usr/local/components/MBU/lib/eccodes/share/eccodes/samples )
  set( ECCODES_IFS_SAMPLES_PATH /usr/local/components/MBU/lib/eccodes/share/eccodes/ifs_samples )
endif()
