FROM centos:7
MAINTAINER Manuel GOACOLOU <mgoacolou@cls.fr>

USER root
ARG VERSION=3.1

RUN  sed -i.bak 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
     sed -i.bak 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
     yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
     yum update -y

RUN yum install -y sudo wget proj proj-devel git rpm-build redhat-rpm-config make \
                   gcc gcc-gfortran xz cmake openssh-clients \
                   libtiff-devel gcc-c++ rpm-sign prelink blas-devel lapack-devel \
                   freetype freetype-devel libjpeg-turbo-devel netcdf-devel hdf5-devel hdf-devel \
                   fftw.x86_64 fftw-devel.x86_64 createrepo bzip2-devel libffi-devel atlas-devel

ENV buildroot=/tmp/build

ENV BASE_DIR="/usr/local/components"
ENV DEST_DIR="${BASE_DIR}/MBU-${VERSION}"

RUN rm -Rf $buildroot && rm -Rf $DEST_DIR && mkdir -p $buildroot$BASE_DIR && mkdir -p $DEST_DIR && mkdir -p $DEST_DIR/bin  && mkdir -p $DEST_DIR/lib

ENV LD_LIBRARY_PATH=$DEST_DIR/lib:$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=/opt/openssl/lib:$LD_LIBRARY_PATH

ENV PYTHON_SHORT_VERSION=3.9
ENV PYTHON_VERSION=$PYTHON_SHORT_VERSION.2
ENV PIP=$DEST_DIR/bin/pip$PYTHON_SHORT_VERSION
ENV PYTHON=$DEST_DIR/bin/python$PYTHON_SHORT_VERSION

ARG nb_cpu_for_compilation=8

RUN wget https://www.openssl.org/source/openssl-1.1.1g.tar.gz && \
    tar zxvf openssl-1.1.1g.tar.gz && \
    cd openssl-1.1.1g && \
    ./config --prefix=$DEST_DIR --openssldir=/opt/openssl no-ssl2 && \
    make -j$nb_cpu_for_compilation && \
    make install

RUN wget https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz --no-check-certificate && \
    tar xzf Python-$PYTHON_VERSION.tgz && \
    cd Python-$PYTHON_VERSION && \
    LDFLAGS="-Wl,-rpath $DEST_DIR/lib" \
        ./configure --prefix=$DEST_DIR \
            --with-openssl=$DEST_DIR \
            --enable-optimizations \
            --with-ensurepip=install \
            --enable-unicode=ucs4  && \
    make -j$nb_cpu_for_compilation build_all && \
    make altinstall && \
    cd .. && \
    rm -Rf Python-$PYTHON_VERSION

RUN $PIP install --no-binary :all: numpy==1.19.5 cython==0.29.21 && \
    $PIP install --no-deps --no-binary :all: cftime==1.0.0 && \
    $PIP install --no-binary :all: "cython<3.0.0" && \
    $PIP install --no-binary :all: netcdf4==1.4.0 && \
    $PIP install --no-binary :all: configobj==5.0.6

ENV PYTHTHON_DEST_DIR=$DEST_DIR

# RUN ln -s $DEST_DIR/lib/libssl.so.1.1 $DEST_DIR/lib/ && \
#     ln -s $DEST_DIR/lib/libcrypto.so.1.1 $DEST_DIR/lib/

RUN yum install -y cmake3 && mkdir -p eccodes/build && cd eccodes && \
    wget https://confluence.ecmwf.int/download/attachments/45757960/eccodes-2.12.0-Source.tar.gz?api=v2 -O eccodes-2.12.0-Source.tar.gz && \
    tar zxf  eccodes-2.12.0-Source.tar.gz && \
    cd build && cmake3 -DCMAKE_INSTALL_PREFIX=$DEST_DIR ../eccodes-2.12.0-Source && \
     make -j$nb_cpu_for_compilation && \
     make install && \
     cd .. && \
     git clone https://github.com/ecmwf/eccodes-python && cd eccodes-python && git checkout 0.8.0 && \
     $DEST_DIR/bin/pip$PYTHON_SHORT_VERSION install  . && \
     cd ../.. && \
     rm -Rf eccodes

# COPY share/eccodes_MBU1.2 $DEST_DIR/share/eccodes_MBU1.2

# create user calcul(1046):boost
RUN export uid=1046 gid=2000 && \
    mkdir -p /home/calcul && \
    echo "calcul:x:${uid}:${gid}:Developer,,,:/home/calcul:/bin/bash" >> /etc/passwd && \
    echo "calcul:x:${uid}:" >> /etc/group && \
    echo "calcul ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    chmod 0440 /etc/sudoers  && \
    chown ${uid}:${gid} -R /home/calcul

USER calcul
# installation of LOP dependencies
CMD sudo $SOURCEDIR/make_LOP_RPM_from_docker.sh
