#!/bin/bash
set -e
VER=3.1
REL=0
export MBUVER=$VER
export MBUREL=$REL

sudo groupadd -g 2000 pic_run
sudo adduser piccontrol --uid 1046 --uid 2000 --shell /bin/tcsh --home /home/piccontrol
sudo sed -i "s;#! /usr/local/bin/python;#! /usr/bin/env python;g" /usr/local/components/MBU-3.1/lib/python3.9/cgi.py

echo "Creating MBU processor RPM version $VER-$REL"

sudo $PIP install /src/
PRJ=/home/user
finalTGT=/usr/local/components/MBU-$VER
TGT=$PRJ/rpmbuild/BUILD/$finalTGT

sudo mkdir -p $finalTGT/share/local_eccodes_definitions
echo copy local eccodes definitions
sudo cp -Rf /src/src/mbu/conf/* $finalTGT/share/local_eccodes_definitions

cd $PRJ
#./build-package

sudo rm -Rf `dirname $TGT`
mkdir -p $TGT

sudo cp -Rfa /usr/local/components/MBU-$VER/* $TGT

cd $TGT/..
echo "ok"
rpmbuild -ba /src/scripts/mbuprocessor-rpm.spec

